/**
 * Central configuration. Every value can be overridden with an environment
 * variable so the same build works locally, on Render and on Railway.
 */
import crypto from 'node:crypto';

const bool = (v, d = false) => (v === undefined ? d : /^(1|true|yes|on)$/i.test(String(v)));
const num = (v, d) => (Number.isFinite(Number(v)) ? Number(v) : d);
const list = (v, d) => (v ? String(v).split(',').map((s) => s.trim()).filter(Boolean) : d);

export const config = {
  env: process.env.NODE_ENV || 'development',
  port: num(process.env.PORT, 3000),
  host: process.env.HOST || '0.0.0.0',

  /** Public origin, used for share links / canonical URLs. */
  baseUrl: process.env.BASE_URL || '',

  /** Branding (kept generic so the deployment can be renamed freely). */
  brandName: process.env.BRAND_NAME || 'WeTube',
  brandTitleSuffix: process.env.BRAND_TITLE_SUFFIX || 'YouTube',
  assetVersion: process.env.ASSET_VERSION || '2.9.60',

  /** Signing key for the session cookie. Autogenerated when missing. */
  sessionSecret:
    process.env.SESSION_SECRET || crypto.randomBytes(32).toString('hex'),
  sessionCookieName: process.env.SESSION_COOKIE_NAME || 'wetube.sid',
  sessionMaxAgeDays: num(process.env.SESSION_MAX_AGE_DAYS, 30),

  /** Language / region used for every YouTube request. */
  hl: process.env.YT_HL || 'ja',
  gl: process.env.YT_GL || 'JP',

  /**
   * Optional HTTP(S) proxy used for YouTube traffic. Railway/Render IPs are
   * frequently blocked by YouTube, so a residential proxy is the reliable fix.
   */
  proxy: process.env.YT_PROXY || process.env.HTTPS_PROXY || '',

  /** Upstream used to resolve direct media URLs (stream mode / downloads). */
  streamProvider: process.env.STREAM_PROVIDER || 'awakest',
  awakestBase: process.env.AWAKEST_BASE || 'https://awakest.net',
  streamTimeoutMs: num(process.env.STREAM_TIMEOUT_MS, 20000),

  /** Comma separated list of alternate embed hosts (edu / mirror players). */
  embedMirrors: list(process.env.EMBED_MIRRORS, []),

  /** Caching */
  cacheTtlSeconds: num(process.env.CACHE_TTL_SECONDS, 300),
  feedCacheTtlSeconds: num(process.env.FEED_CACHE_TTL_SECONDS, 180),
  videoCacheTtlSeconds: num(process.env.VIDEO_CACHE_TTL_SECONDS, 900),
  suggestionsTtlSeconds: num(process.env.SUGGESTIONS_TTL_SECONDS, 3600),
  maxCacheEntries: num(process.env.MAX_CACHE_ENTRIES, 4000),

  /** Optional Redis for multi-replica deployments (sessions + cache). */
  redisUrl: process.env.REDIS_URL || '',

  /** Image proxy hardening */
  imageProxyAllowHosts: list(process.env.IMAGE_PROXY_ALLOW_HOSTS, [
    'i.ytimg.com',
    'yt3.ggpht.com',
    'yt3.googleusercontent.com',
    'yt4.ggpht.com',
    'yt4.googleusercontent.com',
    'lh3.googleusercontent.com',
    'lh4.googleusercontent.com',
    'lh5.googleusercontent.com',
    'lh6.googleusercontent.com',
    'play-lh.googleusercontent.com',
    'www.gstatic.com',
  ]),
  imageProxyMaxBytes: num(process.env.IMAGE_PROXY_MAX_BYTES, 6 * 1024 * 1024),
  allowOpenImageProxy: bool(process.env.IMAGE_PROXY_ALLOW_ANY_HOST, false),

  /** OAuth device flow (TV client). Refreshed from youtube.com at boot. */
  oauthClientId: process.env.OAUTH_CLIENT_ID || '',
  oauthClientSecret: process.env.OAUTH_CLIENT_SECRET || '',
  oauthScope:
    process.env.OAUTH_SCOPE ||
    'https://www.googleapis.com/auth/youtube-third-party-link',
  oauthPollIntervalMs: num(process.env.OAUTH_POLL_INTERVAL_MS, 5000),

  /** Feature flags */
  enableLiveChat: bool(process.env.ENABLE_LIVE_CHAT, true),
  enableDownloads: bool(process.env.ENABLE_DOWNLOADS, true),
  trustProxy: bool(process.env.TRUST_PROXY, true),

  /** Simple rate limiting */
  rateLimitWindowMs: num(process.env.RATE_LIMIT_WINDOW_MS, 60000),
  rateLimitMax: num(process.env.RATE_LIMIT_MAX, 240),
};

export default config;
